# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaffleMarket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 7.1'
  pod 'RxAlamofire', '~> 6.1'
  pod 'RxSwift', '~> 6.2'
  pod 'RxCocoa', '~> 6.2'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRelay', '~> 6.2'
  pod 'RxGesture', '~> 4.0'
  pod 'Moya/RxSwift', '~> 15.0'
  pod 'GoogleSignIn'
end
