# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaffleMarket' do
  platform :ios, '15.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 7.1'
  pod 'RxAlamofire', '~> 6.1'
  pod 'RxSwift', '~> 6.2'
  pod 'RxCocoa', '~> 6.2'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxRelay', '~> 6.2'
  pod 'RxGesture', '~> 4.0'
  pod 'Moya/RxSwift', '~> 15.0'
  pod 'GoogleSignIn'
  pod 'NMapsMap'
  pod 'RxCoreLocation'
  pod 'YPImagePicker'
  pod 'Starscream', '~> 4.0.0'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
